## Assignment 6, Part 2

October 13, 2019

#### Esin Alpturk

In this notebook, I am ingesting a fixed width file that deals with precipitation measurements. This data is used to spot trends in precipitation patterns.

This dataset is provided by the 'National Oceanic and Atmospheric Administration, Department of Commerce'. It includes the monthly U.S. reported precipitation amounts in hundredths of inches (ex 100 is 1.00 inches) generated from the GTS metar(hourly) and synoptic(6-hourly) observations for selected cities based on the Weekly Weather and Crop Bulletin station list. More information can be found by following this link: https://catalog.data.gov/dataset/climate-prediction-center-cpc-monthly-u-s-selected-cities-precipitation-summary

In [1]:
import pandas as pd

I already opened the file in a text editor and discovered that the first __ rows are header/descriptive rows that I want to ignore and not read in.

In [2]:
precip_df = pd.read_fwf('C:/Users/Inspiration/Desktop/module6/mctyprcp.txt', skiprows=10, header=None,
                        colspecs='infer', widths=None)
precip_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,AL,BIRMINGHAM 0,BHM,56.0,-349.0,34.0,2.0,0.0,-999.0,-999.0,3706 -458,89.0
1,AL,HUNTSVILLE 0,HSV,27.0,-402.0,16.0,2.0,0.0,-999.0,-999.0,4549 217,105.0
2,AL,MOBILE 0,MOB,157.0,-444.0,157.0,1.0,1.0,-999.0,-999.0,4643 -633,88.0
3,AL,MONTGOMERY 0,MGM,5.0,-417.0,5.0,1.0,0.0,-999.0,-999.0,3401 -850,80.0
4,AK,ANCHORAGE 0,ANC,378.0,91.0,86.0,9.0,3.0,-999.0,-999.0,971 -213,82.0

And let's look at the end of our data!

In [3]:
precip_df.tail()

,0,1,2,3,4,5,6,7,8,9,10,11
245,WY,CASPER 0,CPR,141.0,43.0,34.0,8.0,0.0,-999.0,-999.0,1630 586,156.0
246,WY,CHEYENNE 0,CYS,51.0,-92.0,16.0,8.0,0.0,-999.0,-999.0,2063 706,152.0
247,WY,LANDER 0,LND,148.0,34.0,58.0,7.0,1.0,-999.0,-999.0,1705 659,163.0
248,WY,SHERIDAN 0,SHR,190.0,52.0,99.0,9.0,1.0,-999.0,-999.0,1812 628,153.0
249,ND,OF DATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The last row of data (249) is the "end of data" and shouldn't be included. Let's get rid of it!

In [4]:
precip_df = precip_df.drop(249)
precip_df.tail()

,0,1,2,3,4,5,6,7,8,9,10,11
244,WI,WAUSAU 0,AUW,733.0,325.0,199.0,7.0,5.0,-999.0,-999.0,3996 1278,147.0
245,WY,CASPER 0,CPR,141.0,43.0,34.0,8.0,0.0,-999.0,-999.0,1630 586,156.0
246,WY,CHEYENNE 0,CYS,51.0,-92.0,16.0,8.0,0.0,-999.0,-999.0,2063 706,152.0
247,WY,LANDER 0,LND,148.0,34.0,58.0,7.0,1.0,-999.0,-999.0,1705 659,163.0
248,WY,SHERIDAN 0,SHR,190.0,52.0,99.0,9.0,1.0,-999.0,-999.0,1812 628,153.0

Also, the second column ("1") has two values in it. We can split this column easily because we know that the last character (position -1) is the "pflag" and that everything else belongs to the city name. Let's create two new columns, city and pflag, which are the result of splitting the combined column.

In [5]:
precip_df['city'] = precip_df[1].str[:-1]  
precip_df['pflag'] = precip_df[1].str[-1]

Let's check it!

In [6]:
precip_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,city,pflag
0,AL,BIRMINGHAM 0,BHM,56.0,-349.0,34.0,2.0,0.0,-999.0,-999.0,3706 -458,89.0,BIRMINGHAM,0
1,AL,HUNTSVILLE 0,HSV,27.0,-402.0,16.0,2.0,0.0,-999.0,-999.0,4549 217,105.0,HUNTSVILLE,0
2,AL,MOBILE 0,MOB,157.0,-444.0,157.0,1.0,1.0,-999.0,-999.0,4643 -633,88.0,MOBILE,0
3,AL,MONTGOMERY 0,MGM,5.0,-417.0,5.0,1.0,0.0,-999.0,-999.0,3401 -850,80.0,MONTGOMERY,0
4,AK,ANCHORAGE 0,ANC,378.0,91.0,86.0,9.0,3.0,-999.0,-999.0,971 -213,82.0,ANCHORAGE,0

Let's remove column 1, since we've captured its data elsewhere.

In [7]:
precip_df = precip_df.drop(columns=[1])
precip_df.head()

,0,2,3,4,5,6,7,8,9,10,11,city,pflag
0,AL,BHM,56.0,-349.0,34.0,2.0,0.0,-999.0,-999.0,3706 -458,89.0,BIRMINGHAM,0
1,AL,HSV,27.0,-402.0,16.0,2.0,0.0,-999.0,-999.0,4549 217,105.0,HUNTSVILLE,0
2,AL,MOB,157.0,-444.0,157.0,1.0,1.0,-999.0,-999.0,4643 -633,88.0,MOBILE,0
3,AL,MGM,5.0,-417.0,5.0,1.0,0.0,-999.0,-999.0,3401 -850,80.0,MONTGOMERY,0
4,AK,ANC,378.0,91.0,86.0,9.0,3.0,-999.0,-999.0,971 -213,82.0,ANCHORAGE,0

It looks like column 10 also needs to be split! We can do this again by position, first 4 (up to but not including position 5) and last 4 (starting with position 5 and continuing until the end)

In [8]:
precip_df['year_to_date_amt'] = precip_df[10].str[:5] 
precip_df['year_to_date_dep_nml'] = precip_df[10].str[5:] 

precip_df = precip_df.drop(columns=[10])
precip_df.head()

,0,2,3,4,5,6,7,8,9,11,city,pflag,year_to_date_amt,year_to_date_dep_nml
0,AL,BHM,56.0,-349.0,34.0,2.0,0.0,-999.0,-999.0,89.0,BIRMINGHAM,0,3706,-458
1,AL,HSV,27.0,-402.0,16.0,2.0,0.0,-999.0,-999.0,105.0,HUNTSVILLE,0,4549,217
2,AL,MOB,157.0,-444.0,157.0,1.0,1.0,-999.0,-999.0,88.0,MOBILE,0,4643,-633
3,AL,MGM,5.0,-417.0,5.0,1.0,0.0,-999.0,-999.0,80.0,MONTGOMERY,0,3401,-850
4,AK,ANC,378.0,91.0,86.0,9.0,3.0,-999.0,-999.0,82.0,ANCHORAGE,0,971 -,213

Now, all we have to do are supply column names and maybe re-order things so that the city and pflag come as the second and third columns, respectively:

In [9]:
precip_df.rename(columns={0:'state',
                          2: "call_ltrs",
                          3: "month_tot_amt",
                          4: "month_dep_nml",
                          5: "24_hr_max",
                          6: "days_gt_1",
                          7: "days_gt_50",
                          8: "season_to_date",
                          9: "season_dep_nml",
                          11: "year_to_date_pct_nml"},inplace=True)

precip_df = precip_df[["state",
                       "city",
                       "pflag",
                       "call_ltrs",
                       "month_tot_amt",
                       "month_dep_nml",
                       "24_hr_max",
                       "days_gt_1",
                       "days_gt_50",
                       "season_to_date",
                       "season_dep_nml",
                       "year_to_date_amt",
                       "year_to_date_dep_nml",
                       "year_to_date_pct_nml"]]

In [10]:
precip_df.head()

,state,city,pflag,call_ltrs,month_tot_amt,month_dep_nml,24_hr_max,days_gt_1,days_gt_50,season_to_date,season_dep_nml,year_to_date_amt,year_to_date_dep_nml,year_to_date_pct_nml
0,AL,BIRMINGHAM,0,BHM,56.0,-349.0,34.0,2.0,0.0,-999.0,-999.0,3706,-458,89.0
1,AL,HUNTSVILLE,0,HSV,27.0,-402.0,16.0,2.0,0.0,-999.0,-999.0,4549,217,105.0
2,AL,MOBILE,0,MOB,157.0,-444.0,157.0,1.0,1.0,-999.0,-999.0,4643,-633,88.0
3,AL,MONTGOMERY,0,MGM,5.0,-417.0,5.0,1.0,0.0,-999.0,-999.0,3401,-850,80.0
4,AK,ANCHORAGE,0,ANC,378.0,91.0,86.0,9.0,3.0,-999.0,-999.0,971 -,213,82.0

Now let's identify the city with the highest and lowest year_to_date_pct_nml. We'll sort first, then we can just look at the first and the last row.

In [11]:
precip_df = precip_df.sort_values(by='year_to_date_pct_nml', ascending=True)

What city has the lowest YTD percent normal precipitation?

In [12]:
precip_df.iloc[0]

state                               NC
city                    HATTERAS
pflag                                2
call_ltrs                          HSE
month_tot_amt                      -99
month_dep_nml                      -99
24_hr_max                          -99
days_gt_1                            9
days_gt_50                           9
season_to_date                    -999
season_dep_nml                    -999
year_to_date_amt                 -999
year_to_date_dep_nml              -999
year_to_date_pct_nml               -99
Name: 153, dtype: object

Oops! There must be something wrong with this information. All look the same. Let's check it further.

In [13]:
precip_df

,state,city,pflag,call_ltrs,month_tot_amt,month_dep_nml,24_hr_max,days_gt_1,days_gt_50,season_to_date,season_dep_nml,year_to_date_amt,year_to_date_dep_nml,year_to_date_pct_nml
153,NC,HATTERAS,2,HSE,-99.0,-99.0,-99.0,9.0,9.0,-999.0,-999.0,-999,-999,-99.0
213,TX,EL PASO,0,ELP,148.0,-13.0,92.0,5.0,1.0,-999.0,-999.0,422 -,318,57.0
45,FL,TALLAHASSEE,0,TLH,0.0,-501.0,0.0,0.0,0.0,-999.0,-999.0,3037-,2199,58.0
13,AZ,PHOENIX,0,PHX,25.0,-50.0,17.0,4.0,0.0,-999.0,-999.0,368 -,216,63.0
220,TX,VICTORIA,0,VCT,369.0,-131.0,240.0,8.0,1.0,-999.0,-999.0,1955-,1099,64.0
27,CO,CO SPRINGS,0,COS,32.0,-91.0,12.0,6.0,0.0,-999.0,-999.0,1009,-543,65.0
219,TX,SAN ANTONIO,0,SAT,146.0,-154.0,87.0,5.0,1.0,-999.0,-999.0,1675,-788,68.0
230,WA,OLYMPIA,0,OLM,343.0,140.0,87.0,4.0,3.0,-999.0,-999.0,2065,-971,68.0
210,TX,CORPUS CHRISTI,0,CRP,419.0,-84.0,79.0,3.0,5.0,-999.0,-999.0,1721,-773,69.0
190,SC,COLUMBIA,0,CAE,196.0,-198.0,101.0,5.0,2.0,-999.0,-999.0,2780-,1135,71.0
54,HI,HILO,0,ITO,772.0,-142.0,124.0,4.0,4.0,-999.0,-999.0,6511-,2532,72.0
155,NC,WILMINGTON,0,ILM,833.0,154.0,581.0,7.0,3.0,-999.0,-999.0,3439-,1271,73.0
53,GA,SAVANNAH,0,SAV,127.0,-381.0,41.0,6.0,0.0,-999.0,-999.0,3107-,1035,75.0
231,WA,QUILLAYUTE,0,UIL,945.0,530.0,249.0,6.0,7.0,-999.0,-999.0,4674-,1558,75.0
10,AK,KODIAK,0,ADQ,443.0,-341.0,101.0,6.0,3.0,-999.0,-999.0,3981-,1257,76.0
52,GA,MACON,0,MCN,2.0,-324.0,2.0,1.0,0.0,-999.0,-999.0,2732,-816,77.0
39,FL,KEY WEST,0,EYW,410.0,-135.0,161.0,3.0,2.0,-999.0,-999.0,2295,-685,77.0
43,FL,PENSACOLA,0,PNS,0.0,-575.0,0.0,0.0,0.0,-999.0,-999.0,3962-,1183,77.0
173,OR,ASTORIA,0,AST,620.0,359.0,154.0,7.0,4.0,-999.0,-999.0,3185,-898,78.0
38,FL,JACKSONVILLE,0,JAX,236.0,-554.0,59.0,1.0,1.0,-999.0,-999.0,3449,-916,79.0
189,SC,CHARLESTON,0,CHS,393.0,-205.0,184.0,5.0,2.0,-999.0,-999.0,3382,-845,80.0
56,HI,KAHULUI,0,OGG,22.0,-17.0,16.0,4.0,0.0,-999.0,-999.0,995 -,248,80.0
3,AL,MONTGOMERY,0,MGM,5.0,-417.0,5.0,1.0,0.0,-999.0,-999.0,3401,-850,80.0
57,HI,LIHUE,0,LIH,325.0,56.0,52.0,5.0,1.0,-999.0,-999.0,2094,-491,81.0
4,AK,ANCHORAGE,0,ANC,378.0,91.0,86.0,9.0,3.0,-999.0,-999.0,971 -,213,82.0
36,FL,FT LAUDERDALE,1,FLL,133.0,-693.0,75.0,0.0,1.0,-999.0,-999.0,4196,-859,83.0
49,GA,ATLANTA,0,ATL,76.0,-333.0,55.0,2.0,1.0,-999.0,-999.0,3233,-662,83.0
178,OR,PORTLAND,0,PDX,387.0,222.0,86.0,4.0,2.0,-999.0,-999.0,1927,-367,84.0
193,SC,MYRTLE BEACH,1,MYR,905.0,347.0,830.0,4.0,2.0,-999.0,-999.0,3014,-574,84.0
208,TX,BROWNSVILLE,0,BRO,419.0,-112.0,228.0,0.0,2.0,-999.0,-999.0,1788,-291,86.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,ND,FARGO,0,FAR,445.0,227.0,137.0,0.0,3.0,-999.0,-999.0,2755,1001,157.0
7,AK,FAIRBANKS,0,FAI,106.0,-6.0,29.0,9.0,0.0,-999.0,-999.0,1252,455,157.0
123,MT,HELENA,0,HLN,304.0,199.0,75.0,1.0,3.0,-999.0,-999.0,1536,564,158.0
197,SD,SIOUX FALLS,0,FSD,288.0,30.0,108.0,0.0,2.0,-999.0,-999.0,3341,1253,160.0
109,MN,ST. CLOUD,0,STC,756.0,463.0,199.0,5.0,6.0,-999.0,-999.0,3621,1358,160.0
115,MO,KANSAS CITY,0,MCI,579.0,115.0,234.0,9.0,4.0,-999.0,-999.0,4909,1841,160.0
119,MT,BILLINGS,0,BIL,324.0,190.0,88.0,2.0,4.0,-999.0,-999.0,1946,738,161.0
160,ND,JAMESTOWN,0,JMS,460.0,286.0,138.0,2.0,5.0,-999.0,-999.0,2587,991,162.0
157,ND,DICKINSON,0,DIK,562.0,400.0,160.0,6.0,2.0,-999.0,-999.0,2300,889,163.0
247,WY,LANDER,0,LND,148.0,34.0,58.0,7.0,1.0,-999.0,-999.0,1705,659,163.0
137,NV,ELY,0,ELY,79.0,-15.0,65.0,5.0,1.0,-999.0,-999.0,1285,502,164.0
15,AR,FORT SMITH,0,FSM,227.0,-134.0,92.0,6.0,2.0,-999.0,-999.0,5234,2062,165.0
125,MT,MILES CITY,0,MLS,233.0,114.0,99.0,0.0,1.0,-999.0,-999.0,1888,751,166.0
240,WI,GREEN BAY,0,GRB,938.0,627.0,209.0,5.0,6.0,-999.0,-999.0,3908,1568,167.0
174,OR,BURNS,0,BNO,112.0,62.0,51.0,8.0,1.0,-999.0,-999.0,1252,507,168.0
139,NV,RENO,0,RNO,30.0,-15.0,22.0,4.0,0.0,-999.0,-999.0,906,370,169.0
207,TX,BEAUMONT,0,BPT,2318.0,1708.0,163.0,9.0,4.0,-999.0,-999.0,7684,3164,170.0
11,AK,NOME,0,OME,437.0,186.0,106.0,0.0,1.0,-999.0,-999.0,2157,889,170.0
132,NE,NORTH PLATTE,0,LBF,95.0,-37.0,41.0,6.0,0.0,-999.0,-999.0,2961,1240,172.0
156,ND,BISMARCK,0,BIS,577.0,416.0,140.0,3.0,4.0,-999.0,-999.0,2501,1056,173.0
162,ND,WILLISTON,0,ISN,811.0,676.0,234.0,5.0,5.0,-999.0,-999.0,2113,906,175.0
127,NE,GRAND ISLAND,0,GRI,137.0,-106.0,50.0,6.0,1.0,-999.0,-999.0,3946,1717,177.0
121,MT,GLASGOW,0,GGW,435.0,337.0,161.0,2.0,4.0,-999.0,-999.0,1733,760,178.0
136,NV,ELKO,0,EKO,240.0,172.0,102.0,0.0,2.0,-999.0,-999.0,1251,560,181.0
108,MN,ROCHESTER,0,RST,843.0,531.0,270.0,7.0,5.0,-999.0,-999.0,4765,2147,182.0
135,NE,VALENTINE,0,VTN,267.0,106.0,102.0,8.0,2.0,-999.0,-999.0,3318,1590,192.0
195,SD,HURON,0,HON,331.0,151.0,113.0,9.0,2.0,-999.0,-999.0,3631,1825,201.0
134,NE,SCOTTSBLUFF,0,BFF,104.0,-18.0,45.0,6.0,0.0,-999.0,-999.0,2808,1411,201.0
196,SD,RAPID CITY,0,RAP,270.0,160.0,117.0,1.0,2.0,-999.0,-999.0,3231,1808,227.0
5,AK,BARROW,0,BRW,93.0,24.0,23.0,3.0,0.0,-999.0,-999.0,930,582,267.0

All look normal except the first row. I will drop it.

In [14]:
precip_df = precip_df.drop(153)

Let's check it again.

In [15]:
precip_df

,state,city,pflag,call_ltrs,month_tot_amt,month_dep_nml,24_hr_max,days_gt_1,days_gt_50,season_to_date,season_dep_nml,year_to_date_amt,year_to_date_dep_nml,year_to_date_pct_nml
213,TX,EL PASO,0,ELP,148.0,-13.0,92.0,5.0,1.0,-999.0,-999.0,422 -,318,57.0
45,FL,TALLAHASSEE,0,TLH,0.0,-501.0,0.0,0.0,0.0,-999.0,-999.0,3037-,2199,58.0
13,AZ,PHOENIX,0,PHX,25.0,-50.0,17.0,4.0,0.0,-999.0,-999.0,368 -,216,63.0
220,TX,VICTORIA,0,VCT,369.0,-131.0,240.0,8.0,1.0,-999.0,-999.0,1955-,1099,64.0
27,CO,CO SPRINGS,0,COS,32.0,-91.0,12.0,6.0,0.0,-999.0,-999.0,1009,-543,65.0
219,TX,SAN ANTONIO,0,SAT,146.0,-154.0,87.0,5.0,1.0,-999.0,-999.0,1675,-788,68.0
230,WA,OLYMPIA,0,OLM,343.0,140.0,87.0,4.0,3.0,-999.0,-999.0,2065,-971,68.0
210,TX,CORPUS CHRISTI,0,CRP,419.0,-84.0,79.0,3.0,5.0,-999.0,-999.0,1721,-773,69.0
190,SC,COLUMBIA,0,CAE,196.0,-198.0,101.0,5.0,2.0,-999.0,-999.0,2780-,1135,71.0
54,HI,HILO,0,ITO,772.0,-142.0,124.0,4.0,4.0,-999.0,-999.0,6511-,2532,72.0
155,NC,WILMINGTON,0,ILM,833.0,154.0,581.0,7.0,3.0,-999.0,-999.0,3439-,1271,73.0
53,GA,SAVANNAH,0,SAV,127.0,-381.0,41.0,6.0,0.0,-999.0,-999.0,3107-,1035,75.0
231,WA,QUILLAYUTE,0,UIL,945.0,530.0,249.0,6.0,7.0,-999.0,-999.0,4674-,1558,75.0
10,AK,KODIAK,0,ADQ,443.0,-341.0,101.0,6.0,3.0,-999.0,-999.0,3981-,1257,76.0
52,GA,MACON,0,MCN,2.0,-324.0,2.0,1.0,0.0,-999.0,-999.0,2732,-816,77.0
39,FL,KEY WEST,0,EYW,410.0,-135.0,161.0,3.0,2.0,-999.0,-999.0,2295,-685,77.0
43,FL,PENSACOLA,0,PNS,0.0,-575.0,0.0,0.0,0.0,-999.0,-999.0,3962-,1183,77.0
173,OR,ASTORIA,0,AST,620.0,359.0,154.0,7.0,4.0,-999.0,-999.0,3185,-898,78.0
38,FL,JACKSONVILLE,0,JAX,236.0,-554.0,59.0,1.0,1.0,-999.0,-999.0,3449,-916,79.0
189,SC,CHARLESTON,0,CHS,393.0,-205.0,184.0,5.0,2.0,-999.0,-999.0,3382,-845,80.0
56,HI,KAHULUI,0,OGG,22.0,-17.0,16.0,4.0,0.0,-999.0,-999.0,995 -,248,80.0
3,AL,MONTGOMERY,0,MGM,5.0,-417.0,5.0,1.0,0.0,-999.0,-999.0,3401,-850,80.0
57,HI,LIHUE,0,LIH,325.0,56.0,52.0,5.0,1.0,-999.0,-999.0,2094,-491,81.0
4,AK,ANCHORAGE,0,ANC,378.0,91.0,86.0,9.0,3.0,-999.0,-999.0,971 -,213,82.0
36,FL,FT LAUDERDALE,1,FLL,133.0,-693.0,75.0,0.0,1.0,-999.0,-999.0,4196,-859,83.0
49,GA,ATLANTA,0,ATL,76.0,-333.0,55.0,2.0,1.0,-999.0,-999.0,3233,-662,83.0
178,OR,PORTLAND,0,PDX,387.0,222.0,86.0,4.0,2.0,-999.0,-999.0,1927,-367,84.0
193,SC,MYRTLE BEACH,1,MYR,905.0,347.0,830.0,4.0,2.0,-999.0,-999.0,3014,-574,84.0
208,TX,BROWNSVILLE,0,BRO,419.0,-112.0,228.0,0.0,2.0,-999.0,-999.0,1788,-291,86.0
144,NM,ALBUQUERQUE,0,ABQ,46.0,-61.0,30.0,4.0,0.0,-999.0,-999.0,635 -,103,86.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,ND,FARGO,0,FAR,445.0,227.0,137.0,0.0,3.0,-999.0,-999.0,2755,1001,157.0
7,AK,FAIRBANKS,0,FAI,106.0,-6.0,29.0,9.0,0.0,-999.0,-999.0,1252,455,157.0
123,MT,HELENA,0,HLN,304.0,199.0,75.0,1.0,3.0,-999.0,-999.0,1536,564,158.0
197,SD,SIOUX FALLS,0,FSD,288.0,30.0,108.0,0.0,2.0,-999.0,-999.0,3341,1253,160.0
109,MN,ST. CLOUD,0,STC,756.0,463.0,199.0,5.0,6.0,-999.0,-999.0,3621,1358,160.0
115,MO,KANSAS CITY,0,MCI,579.0,115.0,234.0,9.0,4.0,-999.0,-999.0,4909,1841,160.0
119,MT,BILLINGS,0,BIL,324.0,190.0,88.0,2.0,4.0,-999.0,-999.0,1946,738,161.0
160,ND,JAMESTOWN,0,JMS,460.0,286.0,138.0,2.0,5.0,-999.0,-999.0,2587,991,162.0
157,ND,DICKINSON,0,DIK,562.0,400.0,160.0,6.0,2.0,-999.0,-999.0,2300,889,163.0
247,WY,LANDER,0,LND,148.0,34.0,58.0,7.0,1.0,-999.0,-999.0,1705,659,163.0
137,NV,ELY,0,ELY,79.0,-15.0,65.0,5.0,1.0,-999.0,-999.0,1285,502,164.0
15,AR,FORT SMITH,0,FSM,227.0,-134.0,92.0,6.0,2.0,-999.0,-999.0,5234,2062,165.0
125,MT,MILES CITY,0,MLS,233.0,114.0,99.0,0.0,1.0,-999.0,-999.0,1888,751,166.0
240,WI,GREEN BAY,0,GRB,938.0,627.0,209.0,5.0,6.0,-999.0,-999.0,3908,1568,167.0
174,OR,BURNS,0,BNO,112.0,62.0,51.0,8.0,1.0,-999.0,-999.0,1252,507,168.0
139,NV,RENO,0,RNO,30.0,-15.0,22.0,4.0,0.0,-999.0,-999.0,906,370,169.0
207,TX,BEAUMONT,0,BPT,2318.0,1708.0,163.0,9.0,4.0,-999.0,-999.0,7684,3164,170.0
11,AK,NOME,0,OME,437.0,186.0,106.0,0.0,1.0,-999.0,-999.0,2157,889,170.0
132,NE,NORTH PLATTE,0,LBF,95.0,-37.0,41.0,6.0,0.0,-999.0,-999.0,2961,1240,172.0
156,ND,BISMARCK,0,BIS,577.0,416.0,140.0,3.0,4.0,-999.0,-999.0,2501,1056,173.0
162,ND,WILLISTON,0,ISN,811.0,676.0,234.0,5.0,5.0,-999.0,-999.0,2113,906,175.0
127,NE,GRAND ISLAND,0,GRI,137.0,-106.0,50.0,6.0,1.0,-999.0,-999.0,3946,1717,177.0
121,MT,GLASGOW,0,GGW,435.0,337.0,161.0,2.0,4.0,-999.0,-999.0,1733,760,178.0
136,NV,ELKO,0,EKO,240.0,172.0,102.0,0.0,2.0,-999.0,-999.0,1251,560,181.0
108,MN,ROCHESTER,0,RST,843.0,531.0,270.0,7.0,5.0,-999.0,-999.0,4765,2147,182.0
135,NE,VALENTINE,0,VTN,267.0,106.0,102.0,8.0,2.0,-999.0,-999.0,3318,1590,192.0
195,SD,HURON,0,HON,331.0,151.0,113.0,9.0,2.0,-999.0,-999.0,3631,1825,201.0
134,NE,SCOTTSBLUFF,0,BFF,104.0,-18.0,45.0,6.0,0.0,-999.0,-999.0,2808,1411,201.0
196,SD,RAPID CITY,0,RAP,270.0,160.0,117.0,1.0,2.0,-999.0,-999.0,3231,1808,227.0
5,AK,BARROW,0,BRW,93.0,24.0,23.0,3.0,0.0,-999.0,-999.0,930,582,267.0

It looks better. Now, let's try to find what city has the lowest YTD percent normal precipitation?

In [16]:
precip_df.iloc[0]

state                               TX
city                    EL PASO
pflag                                0
call_ltrs                          ELP
month_tot_amt                      148
month_dep_nml                      -13
24_hr_max                           92
days_gt_1                            5
days_gt_50                           1
season_to_date                    -999
season_dep_nml                    -999
year_to_date_amt                 422 -
year_to_date_dep_nml               318
year_to_date_pct_nml                57
Name: 213, dtype: object

El Paso, TX has 57% of its year to date normal.

And the city with the highest percent of its normal precipitation?

In [18]:
precip_df.iloc[-1]

state                               AK
city                    BARROW
pflag                                0
call_ltrs                          BRW
month_tot_amt                       93
month_dep_nml                       24
24_hr_max                           23
days_gt_1                            3
days_gt_50                           0
season_to_date                    -999
season_dep_nml                    -999
year_to_date_amt                 930
year_to_date_dep_nml               582
year_to_date_pct_nml               267
Name: 5, dtype: object

Barrow, Alaska is very wet at over twice its normal precipitation!

We've done a lot of work to re-format our data. Let's write this neatned up dataset to file!

In [20]:
precip_df.to_csv('C:/Users/Inspiration/Desktop/module6/precipitation_data.csv')

### Thank you for reading!